export const galleryWorks = [
  {
    id: 1,
    name: 'LiDAR Rastovac',
    src: 'assets/images/works/PolyLiDAR.png',
    link: '/lidar',
    description: 'A 3D scan of an object using LiDAR technology. First parts of this house were built around 1910 by the wealthiest family in the village. In next 30 years it was built apon and finished and the chicken coop was rebuilt in 1940s. Last 15 solitary years of old lady Milka’s life were spent here. She took care of her chickens, the house and the property. Every rain leak, fox brake in, fance repair was done by her. After her passing the old chicken coop was planned for demolition. Because this person and place was a big part of my childhood, I decided to take photos and exact messurments to replicate it as close as possible',
    artistName: 'Kukicrafts',
    artistRealName: 'Josip Kuštan',
    artistsImage: 'assets/images/avatarImage.webp',
  },
  {
    id: 2,
    name: 'Photogrammetry Rastovac',
    src: 'assets/images/works/PolyFotogrametrija.png',
    link: '/photogrammetry',
    description: '3D reconstruction of an object using photogrammetry. First parts of this house were built around 1910 by the wealthiest family in the village. In next 30 years it was built apon and finished and the chicken coop was rebuilt in 1940s. Last 15 solitary years of old lady Milka’s life were spent here. She took care of her chickens, the house and the property. Every rain leak, fox brake in, fance repair was done by her. After her passing the old chicken coop was planned for demolition. Because this person and place was a big part of my childhood, I decided to take photos and exact messurments to replicate it as close as possible',
    artistName: 'Kukicrafts',
    artistRealName: 'Josip Kuštan',
    artistsImage: 'assets/images/avatarImage.webp',
  },
  {
    id: 3,
    name: 'Deimos\'s Axe',
    src: 'assets/images/works/Deimos\'s Axe.png',
    link: '/deimos-axe',
    description: 'A 3D model of Deimos\'s axe from the homebrew D&D game. The model is made in blender and the materials are in substance painter',
    artistName: 'Filip Valjavec',
    artistRealName: 'Filip Valjavec',
    artistsImage: 'assets/images/filipvaljavec.png',
  },
];
