[build]
  command = "npm run build"
  publish = ".next"

[build.environment]
  NODE_VERSION = "24"
  AWS_LAMBDA_JS_RUNTIME = "nodejs22.x"

[[plugins]]
  package = "@netlify/plugin-nextjs"

[[headers]]
  for = "/assets/images/*"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"

[[headers]]
  for = "/assets/objects/*"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"

[[headers]]
  for = "/assets/PDF/*"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"
